{"name": "test_StockSelectionDevice_put01", "status": "broken", "statusDetails": {"message": "pymysql.err.InternalError: (1049, \"Unknown database 't_tactic6'\")", "trace": "self = <TestCase.StockSelectionDevice.test_StockSelectionDevice_01_put.TestStockSelectionDevicePut object at 0x000001B7D5CA5AC0>\n\n    @allure.story('保存策略_1-中国香港')\n    def test_StockSelectionDevice_put01(self):\n        response = zhuorui('选股器', '保存策略_1-中国香港')\n        if response.json().get(\"code\") == \"000000\":\n            assert_data(response, '000000', 'ok')\n        elif response.json().get(\"code\") == \"450001\":\n            assert_data(response, '450001', '策略名称已存在')\n        assert response.status_code == 200\n        # print(response.json())\n        q = OperationSql(\"192.168.1.236\", \"root\", \"123456\", \"t_tactic6\")\n>       Id = str(q.show_sql(\"select _id from t_user_account where `user_id`= '90106be7c8444dda8f0f5b745b50a08e';\"))\n\ntest_StockSelectionDevice_01_put.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\Common\\show_sql.py:56: in show_sql\n    raise e\n..\\..\\Common\\show_sql.py:52: in show_sql\n    cursor = self.get_newCursor()\n..\\..\\Common\\show_sql.py:33: in get_newCursor\n    self._cursor = self.get_connect_sql().cursor()\n..\\..\\Common\\show_sql.py:27: in get_connect_sql\n    self._conn = pymysql.connect(self.address, self.user, self.password, self.database)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\__init__.py:94: in Connect\n    return Connection(*args, **kwargs)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:325: in __init__\n    self.connect()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:599: in connect\n    self._request_authentication()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:861: in _request_authentication\n    auth_packet = self._read_packet()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:684: in _read_packet\n    packet.check_error()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff\\x19\\x04#42000Unknown database 't_tactic6'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1049, \"Unknown database 't_tactic6'\")\n\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\err.py:109: InternalError"}, "start": 1595929680946, "stop": 1595929681029, "uuid": "a60750fe-715d-43a7-9741-dbbb9a19988b", "historyId": "cd091e30e3ac5f2c4c6c3cff812b68b0", "testCaseId": "4f07daa2bdcec88b7a030df68ba7e5ff", "fullName": "TestCase.StockSelectionDevice.test_StockSelectionDevice_01_put.TestStockSelectionDevicePut#test_StockSelectionDevice_put01", "labels": [{"name": "feature", "value": "选股器"}, {"name": "story", "value": "保存策略_1-中国香港"}, {"name": "parentSuite", "value": "TestCase.StockSelectionDevice"}, {"name": "suite", "value": "test_StockSelectionDevice_01_put"}, {"name": "subSuite", "value": "TestStockSelectionDevicePut"}, {"name": "host", "value": "DESKTOP-KBU1G8M"}, {"name": "thread", "value": "17504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.StockSelectionDevice.test_StockSelectionDevice_01_put"}]}