{"uuid": "280f2a0d-0bb5-4ac5-9721-c3310f1d1af0", "children": ["c0e7ca87-1be4-4fed-b12e-421b0e9b37b4"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'TestData/hsgtis_lgt.json'\n", "trace": "  File \"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\zrapiautotestv1.0\\TestCase\\StockQuotation\\HSGTstockRelevance\\test_HSGTstock_Ifhsgtis_lgt.py\", line 32, in setup_class\n    with open(r\"TestData/hsgtis_lgt.json\", \"w\", encoding=\"utf-8\") as f:\n"}, "start": 1597886388308, "stop": 1597886388396}], "start": 1597886388308, "stop": 1597886388587}