{"uuid": "fe2ee2a3-c750-424a-ad4e-cd62a83dd6a5", "children": ["0a0fb649-0ef0-4689-a391-0b3a0b870b93", "0adfc929-ef26-435b-8bcd-57d419570fcd"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\python\\zrapiautotestv1.0\\TestCase\\StockQuotation\\OptionalStock\\test_stick_optional_stock.py\", line 17, in setup_class\n    cls._id = {\"id\": str(id[5].get('_id'))}\n"}, "start": 1594176369370, "stop": 1594176369421}], "start": 1594176369370, "stop": 1594176369432}